### ISSUE TITLE
Publish Stable Nuget Package

### ISSUE THREAD

**Issue by richardlawley** [CloudNimble/TypeLitePlus#4]
Would it be possible to publish a stable nuget package?  At the moment the only versions published are all flagged as pre-release, which prevents any nuget packages depending on it unless they are also pre-release.  

From what I can tell, 2.0.1-CI-20190303-180147 is built from your 2.1.0 source, so should ideally be published to nuget as stable 2.1.0.

**Comment by robertmclaws** [comment]
Your wish is my command. 2.1.0 stable has been released!

Also, I saw your extensions to generate Knockout files... happy to take a pull request if you'd like to include it. :)
